/**
 * Companion to generate-datasets.ts: appends the table rows and per-dataset
 * sections for the same SPECS array into data/SOURCES.md. Kept as a separate
 * script rather than folded into generate-datasets.ts's automatic file
 * writes, because SOURCES.md is meant to be hand-reviewed prose - this
 * writes a well-formed first draft of that prose, not a finished one.
 *
 * Run once with: node --disable-warning=MODULE_TYPELESS_PACKAGE_JSON scripts/append-sources.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { interpolateAnnualSeries } from "../lib/datasets/interpolate.ts";
import { SPECS } from "./generate-datasets.ts";

const rows = SPECS;

const current = readFileSync("data/SOURCES.md", "utf8");

// Idempotent: skip any slug that already has a heading in the file, so
// re-running after adding new SPECS entries only appends what's new.
const alreadyPresent = new Set(
  [...current.matchAll(/^## `([a-z0-9-]+)`$/gm)].map((m) => m[1]),
);
const newRowsOnly = rows.filter((s) => !alreadyPresent.has(s.slug));

if (newRowsOnly.length === 0) {
  console.log("append-sources: nothing new to add, every slug already has a section");
  process.exit(0);
}

const newTableRows = newRowsOnly
  .map(
    (s) =>
      `| \`${s.slug}\` | ${s.sourceName} | ${s.sourceUrl} | not yet retrieved | **NO** | See notes below |`,
  )
  .join("\n");

const newSections = newRowsOnly
  .map((s) => {
    const { xValues } = interpolateAnnualSeries(s.anchors);
    return `## \`${s.slug}\`

**Status: UNVERIFIED. Do not publish, do not quote, do not activate.**

Series generated by \`scripts/generate-datasets.ts\` from real, sourced anchor
points (real years, real approximate values) at ${s.anchors
      .map((a) => a.year)
      .join(
        ", ",
      )}, connected by straight lines. Everything between those anchor years
is an interpolation guess, not a measured value - a human needs to pull the
exact annual series (${xValues[0]}-${xValues[xValues.length - 1]}) before this
ships.

**What is needed to verify:** the exact annual series from ${s.sourceName},
${s.methodologyNote}

**Known discontinuities to check when the real series arrives:**

${s.discontinuities}

**The perception-gap claim behind this dataset:** ${s.perceptionGap}

**Once verified:** set \`verified: true\`, set \`verifiedOn\` to the ISO date,
set \`isActive: true\`, fill in the retrieval date above, and remove the
\`TODO: verify against\` comment from the dataset file.`;
  })
  .join("\n\n---\n\n");

const updated = current
  .replace(
    "| `us-teen-birth-rate` | CDC / National Center for Health Statistics (NCHS), Natality files | https://wonder.cdc.gov/natality.html | not yet retrieved | **NO** | See notes below |",
    `| \`us-teen-birth-rate\` | CDC / National Center for Health Statistics (NCHS), Natality files | https://wonder.cdc.gov/natality.html | not yet retrieved | **NO** | See notes below |\n${newTableRows}`,
  )
  .trimEnd() + `\n\n---\n\n${newSections}\n`;

writeFileSync("data/SOURCES.md", updated);
console.log(`append-sources: added ${newRowsOnly.length} row(s) and section(s) to data/SOURCES.md`);
